@echo off
setlocal
set starttime=%time%

:: string begins with a period needs to be quoted
SET directive=
SET otfn=mesmer.test

IF EXIST "../Windows VC16/Mesmer/Mesmer.exe" GOTO VC16
IF EXIST "../Windows VC17/Mesmer/Mesmer.exe" GOTO VC17

::For installed version
SET executable="../../Mesmer.exe"
GOTO SETTINGS

:VC16
SET executable="../../Windows VC16/Mesmer/Mesmer.exe"
GOTO SETTINGS

:VC17
SET executable="../../Windows VC17/Mesmer/Mesmer.exe"
GOTO SETTINGS

:SETTINGS
SET tfn=mesmer.test
SET lfn=mesmer.log
SET bline=baselines\Win32\
SET outf=out.xml
SET mpicommand="C:\Program Files\Microsoft MPI\Bin\mpiexec" -n 4 %executable%
SET cmdline=%mpicommand%
::SET cmdline=%mpicommand%

:: This compares the "double quote" altogether with the content
IF "%1"=="" (
SET directive=-q
SET otfn=test.test
echo.
echo -------------------------------------------------------------------------------------------------------------
echo User QA check mode: output will copy to test.test in the baselines folder. Use your own "diff" program to 
echo check changes between test.test and mesmer.test in baseline folders. Please ensure the original files in 
echo the baseline folders were not previously modified by user.
echo -------------------------------------------------------------------------------------------------------------
echo.
GOTO RUNNING
)
IF "%1"=="-o" (
echo.
echo -------------------------------------------------------------------------------
echo Developer QA check mode: output will overwrite the baselines. Use
echo "SVN check for modifications" to check the changes compared with the baselines.
echo -------------------------------------------------------------------------------
echo.
GOTO RUNNING
)

echo.
echo -------------------------------------------------------------------------------------------------------------
echo This file execute mesmer executable on several quality assessment files. There are two options to execute this file:
echo.
echo 1. user test mode; simply to confirm that if the files (mesmer.test) generated by current machine
echo    is identical to the mesmer baselines.
echo.
echo Syntax:
echo.
echo "\MESMER_PATH\MesmerQA>QA"
echo.
echo 2. developer SVN test mode; it overwrites mesmer.test files in the baseline folders, thus the developer can use
echo    SVN check for modifications from the MesmerQA folder to see what files are changed and the detail of the modifications.
echo    To use it in the developer mode simply give a -o directive after QA command.
echo.
echo Syntax:
echo.
echo "\MESMER_PATH\MesmerQA>QA -o"
echo -------------------------------------------------------------------------------------------------------------
echo.
GOTO END

:RUNNING
REM GOTO IN

cd AcetylO2
:: display mesmer version
%executable% -V

%cmdline% Acetyl_O2_associationEx.xml -o %outf% %directive%
copy "./%tfn%" "./%bline%%otfn%"
IF "%1"=="-o" copy "./%lfn%" "./%bline%%lfn%"
cd ..

cd AcetylPrior
%cmdline% AcetylPrior.xml -o %outf% %directive%
copy "./%tfn%" "./%bline%%otfn%"
IF "%1"=="-o" copy "./%lfn%" "./%bline%%lfn%"
cd ..

cd Butyl_H_to_Butane
%cmdline% Butyl_H_to_Butane.xml -o %outf% %directive%
copy "./%tfn%" "./%bline%%otfn%"
IF "%1"=="-o" copy "./%lfn%" "./%bline%%lfn%"
cd ..

cd Ethyl_H_to_Ethane
set testName="Ethyl_H_to_Ethane"
%cmdline% -N %testName%.xml
copy "./%testName%.test" "./%bline%%testName%.test"
IF "%1"=="-o" copy "./%testName%.log" "./%bline%%testName%.log"

set testName="Ethyl_H_to_Ethane_inversion"
%cmdline% -N %testName%.xml
copy "./%testName%.test" "./%bline%%testName%.test"
IF "%1"=="-o" copy "./%testName%.log" "./%bline%%testName%.log"
cd ..

cd i-propyl
%cmdline% ipropyl_LM.xml -o %outf% %directive%
copy "./%tfn%" "./%bline%%otfn%"
IF "%1"=="-o" copy "./%lfn%" "./%bline%%lfn%"
cd ..

cd Methyl_H_to_Methane
%cmdline% Methyl_H_to_Methane.xml -o %outf% %directive%
copy "./%tfn%" "./%bline%%otfn%"
IF "%1"=="-o" copy "./%lfn%" "./%bline%%lfn%"

%cmdline% -N Methyl_H_to_Methane_FTST.xml %directive%
copy Methyl_H_to_Methane_FTST.test "./%bline%Methyl_H_to_Methane_FTST.test"
IF "%1"=="-o" copy Methyl_H_to_Methane_FTST.log "./%bline%Methyl_H_to_Methane_FTST.log"
cd ..

cd reservoirSink
%cmdline% reservoirSinkAcetylO2.xml -o %outf% %directive%
copy "./%tfn%" "./%bline%%otfn%"
IF "%1"=="-o" copy "./%lfn%" "./%bline%%lfn%"
cd ..

cd spin_forbidden_kinetics
%cmdline% -N HCCH_methylene.xml %directive%
copy "./HCCH_methylene.test" "./%bline%HCCH_methylene.test"
IF "%1"=="-o" copy "./HCCH_methylene.log" "./%bline%HCCH_methylene.log"

%cmdline% -N LZ_test.xml %directive%
copy "./LZ_test.test" "./%bline%LZ_test.test"
IF "%1"=="-o" copy "./LZ_test.log" "./%bline%LZ_test.log"

%cmdline% -N WKB_test.xml %directive%
copy "./WKB_test.test" "./%bline%WKB_test.test"
IF "%1"=="-o" copy "./WKB_test.log" "./%bline%WKB_test.log"

set testName="ZNtest"
%cmdline% -N %testName%.xml
copy "./%testName%.test" "./%bline%%testName%.test"
IF "%1"=="-o" copy "./%testName%.log" "./%bline%%testName%.log"
cd ..

cd "OH_NO_to HONO"
%cmdline% OH_NO_HONO.xml -o %outf% %directive%
copy "./%tfn%" "./%bline%%otfn%"
IF "%1"=="-o" copy "./%lfn%" "./%bline%%lfn%"
cd ..

cd "OH-acetylene"
%cmdline% OH_HCCH-irreversibleBim-publish.xml -o %outf% %directive%
copy "./%tfn%" "./%bline%%otfn%"
IF "%1"=="-o" copy "./%lfn%" "./%bline%%lfn%"
cd ..

cd "AnalyticalRepresentation"
set testName="Chebyshev"
%cmdline% -N %testName%.xml
copy "./%testName%.test" "./%bline%%testName%.test"
IF "%1"=="-o" copy "./%testName%.log" "./%bline%%testName%.log"
set testName="ChebyshevCK"
%cmdline% -N %testName%.xml
copy "./%testName%.test" "./%bline%%testName%.test"
IF "%1"=="-o" copy "./%testName%.log" "./%bline%%testName%.log"
set testName="Plog"
%cmdline% -N %testName%.xml
copy "./%testName%.test" "./%bline%%testName%.test"
IF "%1"=="-o" copy "./%testName%.log" "./%bline%%testName%.log"
set testName="PlogCK"
%cmdline% -N %testName%.xml
copy "./%testName%.test" "./%bline%%testName%.test"
IF "%1"=="-o" copy "./%testName%.log" "./%bline%%testName%.log"
cd ..

cd "SensitivityAnalysis"
set testName="ipropyl_SA"
%cmdline% -N %testName%.xml
copy "./%testName%.test" "./%bline%%testName%.test"
IF "%1"=="-o" copy "./%testName%.log" "./%bline%%testName%.log"
set testName="pentyl_isomerization_SA"
%cmdline% -N %testName%.xml
copy "./%testName%.test" "./%bline%%testName%.test"
IF "%1"=="-o" copy "./%testName%.log" "./%bline%%testName%.log"
cd ..

cd "cis_to_trans_But-2-ene"
set testName="cis_to_trans_But-2-ene"
%cmdline% -N %testName%.xml
copy "./%testName%.test" "./%bline%%testName%.test"
IF "%1"=="-o" copy "./%testName%.log" "./%bline%%testName%.log"
set testName="cis_to_trans_But-2-eneEx"
%cmdline% -N %testName%.xml
copy "./%testName%.test" "./%bline%%testName%.test"
IF "%1"=="-o" copy "./%testName%.log" "./%bline%%testName%.log"
cd ..

cd "C4H9O2_NO2_to_C4H9O2NO2"
set testName="C4H9O2_NO2_association"
%cmdline% -N %testName%.xml
copy "./%testName%.test" "./%bline%%testName%.test"
IF "%1"=="-o" copy "./%testName%.log" "./%bline%%testName%.log"
cd ..

cd "CH3O2_NO2_to_CH3O2NO2"
set testName="CH3O2_NO2_associationEx2"
%cmdline% -N %testName%.xml
copy "./%testName%.test" "./%bline%%testName%.test"
IF "%1"=="-o" copy "./%testName%.log" "./%bline%%testName%.log"
cd ..

cd "ErrorPropagation"
set testName="ipropyl_EP"
%cmdline% -N %testName%.xml
copy "./%testName%.test" "./%bline%%testName%.test"
IF "%1"=="-o" copy "./%testName%.log" "./%bline%%testName%.log"
cd ..

cd "2Methyl_to_Ethane"
set testName="CH3_CH3_to_C2H6"
%cmdline% -N %testName%.xml
copy "./%testName%.test" "./%bline%%testName%.test"
IF "%1"=="-o" copy "./%testName%.log" "./%bline%%testName%.log"
cd ..

cd "Glyoxyl"
set testName="Glyoxal"
%cmdline% -N %testName%.xml
copy "%testName%.test" %bline%
IF "%1"=="-o" copy "./%testName%.log" "./%bline%%testName%.log"

set testName="Glyoxal_Exchange"
%cmdline% -N %testName%.xml
copy "%testName%.test" %bline%
IF "%1"=="-o" copy "./%testName%.log" "./%bline%%testName%.log"
cd ..

cd "DefinedTunellingCoefficients"
set testName=OH+methanol
%cmdline% -N "%testName%.xml"
copy "%testName%.test" %bline%
IF "%1"=="-o" copy "./%testName%.log" "./%bline%%testName%.log"
cd ..

cd "diamond"
set testName="diamond-gaussianModel"
%cmdline% -N %testName%.xml
copy "./%testName%.test" "./%bline%%testName%.test"
IF "%1"=="-o" copy "./%testName%.log" "./%bline%%testName%.log"
cd ..

cd "Tunnelling"
set testName=H+H2,T+T2
%cmdline% -N %testName%.xml
copy "%testName%.test" %bline%
IF "%1"=="-o" copy "./%testName%.log" "./%bline%%testName%.log"
set testName="Acetyl_O2_associationEx1"
%cmdline% -N %testName%.xml
copy "./%testName%.test" "./%bline%%testName%.test"
IF "%1"=="-o" copy "./%testName%.log" "./%bline%%testName%.log"
set testName="Acetyl_O2_associationEx2"
%cmdline% -N %testName%.xml
copy "./%testName%.test" "./%bline%%testName%.test"
IF "%1"=="-o" copy "./%testName%.log" "./%bline%%testName%.log"
cd ..

cd "CoupledRotors"
set testName="ipropyl_UCR"
%cmdline% -N %testName%.xml
IF "%1"=="-o" copy "./mesmer_out.xml" "./%bline%%testName%_out.xml"
set testName="ipropyl_UQR"
%cmdline% -N %testName%.xml
IF "%1"=="-o" copy "./mesmer_out.xml" "./%bline%%testName%_out.xml"
set testName="ipropyl_CCR"
%cmdline% -N %testName%.xml
IF "%1"=="-o" copy "./mesmer_out.xml" "./%bline%%testName%_out.xml"
set testName="Octyl_H_to_Octane_UCR"
%cmdline% -N %testName%.xml
IF "%1"=="-o" copy "./mesmer_out.xml" "./%bline%%testName%_out.xml"
set testName="Octyl_H_to_Octane_UQR"
%cmdline% -N %testName%.xml
IF "%1"=="-o" copy "./mesmer_out.xml" "./%bline%%testName%_out.xml"
set testName="Octyl_H_to_Octane_CCR"
%cmdline% -N %testName%.xml
IF "%1"=="-o" copy "./mesmer_out.xml" "./%bline%%testName%_out.xml"
cd ..

cd "OH_Ethene"
set testName="Ethylene_abstraction"
%cmdline% -N %testName%.xml
copy "./%testName%.test" "./%bline%%testName%.test"
IF "%1"=="-o" copy "./%testName%.log" "./%bline%%testName%.log"
cd ..

cd "Methyl_O_to_Methoxy"
set testName="Methyl_O_to_Methoxy"
%cmdline% -N %testName%.xml
copy "./%testName%.test" "./%bline%%testName%.test"
IF "%1"=="-o" copy "./%testName%.log" "./%bline%%testName%.log"
cd ..

cd "POandO2"
set testName=PO+O2
%cmdline% -N "%testName%.xml"
copy "%testName%.test" %bline%
IF "%1"=="-o" copy "./%testName%.log" "./%bline%%testName%.log"
cd ..

cd "H2Ominimal"
set testName="H2Ominimal"
%cmdline% -N %testName%.xml
copy "./%testName%.test" "./%bline%%testName%.test"
IF "%1"=="-o" copy "./%testName%.log" "./%bline%%testName%.log"

set testName="H2OBend"
%cmdline% -N %testName%.xml
copy "./%testName%.test" "./%bline%%testName%.test"
IF "%1"=="-o" copy "./%testName%.log" "./%bline%%testName%.log"
cd ..

cd "Butan-1-ol"
set testName="Butoxy_H_to_Butan-1-ol"
%cmdline% -N %testName%.xml
copy "./%testName%.test" "./%bline%%testName%.test"
IF "%1"=="-o" copy "./%testName%.log" "./%bline%%testName%.log"

set testName="Butan-1-peroxy_H_to_Butan-1-hydroperoxy"
%cmdline% -N %testName%.xml
copy "./%testName%.test" "./%bline%%testName%.test"
IF "%1"=="-o" copy "./%testName%.log" "./%bline%%testName%.log"
cd ..

cd "InternalRotor"
set testName=InternalRotor
%cmdline% -N "%testName%.xml"
copy "%testName%.test" %bline%
IF "%1"=="-o" copy "./%testName%.log" "./%bline%%testName%.log"
cd ..

:OUT

echo Start Time=%starttime% - End Time=%time%

:: This line below makes DOS to create a system Beep (err yup)
echo 
echo 
echo 

:END
